INSERT INTO Customers(email,password) VALUES

('drizzello1i@1und1.de','fPL9F96SVFcR'),
('pmatzke2d@jimdo.com','4Px3iL'),
('rkrale6c@i2i.jp','VAZDUbZ'),
('pedscer9g@sun.com','5NKFEBM2pF2'),
('twegnerat@shop-pro.jp','G0qTWqal9o'),
('schappelowd7@scientificamerican.com','o1ICWsOb'),
('tbroadleydh@rambler.ru','BEJdbDQ'),
('bjellimanfb@globo.com','UAhH1avBa4'),
('rblatcherfx@sakura.ne.jp','PSWXtbnTJ3L'),
('scorradinofy@indiegogo.com','WKRUIzItMmjc'),
('rmorrelh2@ftc.gov','JgySZ2F'),
('lcossletthm@uiuc.edu','z0QK7nEcJ'),
('acorsarih@theguardian.com','Rm3gK0jloovp'),
('mblachfordiv@ask.com','8aXdsI0NuZKO'),
('bstaningl9@privacy.gov.au','aZwdC0nJggBs'),
('alelj@ovh.net','AZxTRKd68x'),
('kyakolevmb@soundcloud.com','xrRkLqq'),
('cbellin1@hexun.com','9KMqO4B'),
('tbourgaizene@privacy.gov.au','6wqF3A62FYD'),
('agreetlandoi@microsoft.com','9dj7et8LxF'),
('abeddoeok@illinois.edu','5Yeb83HeeWxI'),
('mrevellepb@nasa.gov','qkCdIov'),
('mrymourpd@hugedomains.com','RtxfZcyW4'),
('pdoolanqt@delicious.com','1w50Bow2');
