CONNECT TO cs421;
/* part 2 */
CREATE TABLE Customers
(
    email VARCHAR(30) NOT NULL PRIMARY KEY,
    password VARCHAR(30) NOT NULL
);

CREATE TABLE Billing_addresses
(aid BIGINT NOT NULL PRIMARY KEY,
 address VARCHAR(100) NOT NULL,
 address2 VARCHAR(100) NOT NULL,
 city VARCHAR(100) NOT NULL,
 province VARCHAR(100) NOT NULL,
 country VARCHAR(5) NOT NULL,
 postal_code VARCHAR(20) NOT NULL,
 phone VARCHAR(20) NOT NULL,
 name VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
FOREIGN KEY (email) REFERENCES Customers);


CREATE TABLE Stadium_addresses
(aid BIGINT NOT NULL PRIMARY KEY,
 address VARCHAR(100) NOT NULL,
 city VARCHAR(100) NOT NULL,
 province VARCHAR(100) NOT NULL,
 country VARCHAR(100) NOT NULL);

DROP TABLE Games_P2;

CREATE TABLE Games_P2
(gname VARCHAR(30) NOT NULL PRIMARY KEY,
 date DATE NOT NULL,
 time VARCHAR (30) NOT NULL,
 aid BIGINT NOT NULL,
 FOREIGN KEY (aid) REFERENCES Stadium_addresses);

CREATE TABLE Credit_cards
(c_num INT NOT NULL PRIMARY KEY,
 cvv INT NOT NULL,
 e_date DATE NOT NULL,
 aid INT NOT NULL,
 FOREIGN KEY (aid) REFERENCES Billing_addresses);

CREATE TABLE Tickets
(tid INT NOT NULL PRIMARY KEY,
 section VARCHAR(1) NOT NULL,
 row INT NOT NULL,
 seat INT NOT NULL,
 gname VARCHAR(30) NOT NULL,
 listed_price INT NOT NULL,
 FOREIGN KEY (gname) REFERENCES Games_P2);


CREATE TABLE Sold_tickets
(tid VARCHAR(100) NOT NULL PRIMARY KEY,
 section VARCHAR(1) NOT NULL,
 row INT NOT NULL,
 seat INT NOT NULL,
 gname VARCHAR(30) NOT NULL,
 listed_price FLOAT NOT NULL,
 sold_price FLOAT NOT NULL,
 sold_date DATE NOT NULL,
 FOREIGN KEY (gname) REFERENCES Games_P2);

CREATE TABLE Purchases
(tid INT NOT NULL,
 c_num INT NOT NULL,
 email VARCHAR(30) NOT NULL,
 gname VARCHAR(30),
 transaction_id VARCHAR(50) NOT NULL,
 t_date DATE NOT NULL,
 t_time TIME NOT NULL,
 PRIMARY KEY (tid),
 FOREIGN KEY (tid) REFERENCES Sold_tickets,
 FOREIGN KEY (email) REFERENCES Customers,
 FOREIGN KEY (c_num) REFERENCES Credit_cards);

